genes:
  - H2AFX      # H2A.X
  - H2AFY      # macroH2A.1  
  - H2AFY2     # macroH2A.2
  - H2AFZ      # H2A.Z

cancer_types:
  - BRCA       
  #add other cancer types

analysis_parameters:
  log2fc_threshold: 1.0
  pvalue_threshold: 0.05
  min_samples: 10

tools:
- GEPIA2: http://gepia.cancer-pku.cn/detail.php?gene=$genename&tag=$tagname

datasets:
  TCGA:
    api_base: "https://api.gdc.cancer.gov"
    endpoints:
      files: "/files"          
      cases: "/cases"          # clinical infos
      projects: "/projects"
    
  recount3:
    base_url: "http://duffel.rail.bio/recount3"
    data_path: "/human/data_sources/tcga/gene_sums"